Load Library

In [1]:
import os
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

 Data Path

In [2]:
RAW_DATA_PATH = r"C:\Users\mayank\OneDrive\Desktop\Project-FORESIGHT\Data\raw"
PROCESSED_DATA_PATH = r"C:\Users\mayank\OneDrive\Desktop\Project-FORESIGHT\Data\cleaned"

print("Raw Data Path :", RAW_DATA_PATH)
print("Processed Path :", PROCESSED_DATA_PATH)

Raw Data Path : C:\Users\mayank\OneDrive\Desktop\Project-FORESIGHT\Data\raw
Processed Path : C:\Users\mayank\OneDrive\Desktop\Project-FORESIGHT\Data\cleaned

 Load CSV Files

In [3]:
sales = pd.read_csv(RAW_DATA_PATH + "\\" + "bm_sales.csv")

inventory = pd.read_csv(RAW_DATA_PATH + "\\" + "bm_inventory.csv")

sku = pd.read_csv(RAW_DATA_PATH + "\\" + "bm_skus.csv")

stores = pd.read_csv(RAW_DATA_PATH + "\\" + "bm_stores.csv")

customers = pd.read_csv(RAW_DATA_PATH + "\\" + "bm_customers.csv")

promotions = pd.read_csv(RAW_DATA_PATH + "\\" + "bm_promotions.csv")

Store Dataframe in dictionary

In [4]:
datasets = {
    "Sales": sales,
    "Inventory": inventory,
    "SKU": sku,
    "Stores": stores,
    "Customers": customers,
    "Promotions": promotions
}

Shape of data

In [5]:
for name, df in datasets.items():
    print(f"{name}")
    print(df.shape)

Sales
(641843, 9)
Inventory
(8735, 7)
SKU
(200, 7)
Stores
(50, 5)
Customers
(5000, 7)
Promotions
(33, 6)

See the record

In [6]:
for name, df in datasets.items():

    print("\n")
    print("="*100)
    print(name)
    print("="*100)

    display(df.head())

====================================================================================================
Sales
====================================================================================================

,date,store_id,sku_id,customer_id,quantity,unit_price,total_value,channel,discount_pct
0,2021-01-01,26,1124,2961.0,1,20.08,20.08,Store,15.0
1,2021-01-01,19,1035,NaN,3,208.57,625.71,Store,15.0
2,2021-01-01,38,1088,NaN,1,17.99,17.99,Website,15.0
3,2021-01-01,3,1164,3694.0,6,196.24,1177.44,Website,0.0
4,2021-01-01,2,1093,1252.0,1,7.98,7.98,Store,0.0

====================================================================================================
Inventory
====================================================================================================

,store_id,sku_id,stock_on_hand,reorder_point,safety_stock,last_restock_date,snapshot_date
0,9,1101,300,92,46,2025-10-18,2025-10-31
1,9,1021,425,162,81,2025-10-21,2025-10-31
2,9,1200,252,85,42,2025-09-14,2025-10-31
3,9,1041,220,87,43,2025-10-13,2025-10-31
4,9,1092,170,80,40,2025-09-12,2025-10-31

====================================================================================================
SKU
====================================================================================================

,sku_id,sku_name,category,subcategory,unit_price,cost_price,brand
0,1001,Electronics_Chargers_1001,Electronics,Chargers,164.56,103.44,Budget
1,1002,Dairy_Cream_1002,Dairy,Cream,13.73,8.96,Local
2,1003,Household_Cleaning Supplies_1003,Household,Cleaning Supplies,12.00,7.47,BlueMart
3,1004,Beverages_Juices_1004,Beverages,Juices,24.82,17.58,International
4,1005,Household_Paper Products_1005,Household,Paper Products,17.70,13.68,Budget

====================================================================================================
Stores
====================================================================================================

,store_id,store_name,city,store_type,opening_date
0,9,BlueMart Store 09,Abu Dhabi,Mall,2017-01-01 00:00:00.000000000
1,10,BlueMart Store 10,Abu Dhabi,Mall,2017-01-31 00:00:00.000000000
2,11,BlueMart Store 11,Dubai,Mall,2017-03-02 00:00:00.000000000
3,12,BlueMart Store 12,Sharjah,Mall,2017-04-01 00:00:00.000000000
4,13,BlueMart Store 13,Sharjah,Community,2017-05-01 00:00:00.000000000

====================================================================================================
Customers
====================================================================================================

,cust_id,age,gender,city,loyalty_segment,preferred_channel,registration_date
0,1,50,Male,Sharjah,Silver,MobileApp,2024-06-29
1,2,20,Female,Abu Dhabi,Gold,Store,2024-12-03
2,3,55,Male,Dubai,Gold,Website,2023-09-18
3,4,25,Male,Abu Dhabi,Platinum,Store,2022-01-02
4,5,20,Female,Abu Dhabi,Silver,MobileApp,2021-09-13

====================================================================================================
Promotions
====================================================================================================

,promo_name,start_date,end_date,discount_pct,promo_type,promo_id
0,Ramadan Sale 2021,2021-04-13,2021-05-12,25,Ramadan,1
1,Eid Al Fitr Sale 2021,2021-05-13,2021-05-15,20,Eid,2
2,Eid Al Adha Sale 2021,2021-07-20,2021-07-22,25,Eid,3
3,Dubai Shopping Festival 2021,2021-01-01,2021-02-28,15,DSF,4
4,Black Friday 2021,2021-11-26,2021-11-28,30,Black Friday,5

Dataset information

In [7]:
for name, df in datasets.items():

    print("="*60)
    print(name)
    print("="*60)

    print(df.info())

============================================================
Sales
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 641843 entries, 0 to 641842
Data columns (total 9 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   date          641843 non-null  object
 1   store_id      641843 non-null  int64
 2   sku_id        641843 non-null  int64
 3   customer_id   482022 non-null  float64
 4   quantity      641843 non-null  int64
 5   unit_price    641843 non-null  float64
 6   total_value   641843 non-null  float64
 7   channel       641843 non-null  object
 8   discount_pct  641843 non-null  float64
dtypes: float64(4), int64(3), object(2)
memory usage: 44.1+ MB
None
============================================================
Inventory
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8735 entries, 0 to 8734
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   store_id           8735 non-null   int64
 1   sku_id             8735 non-null   int64
 2   stock_on_hand      8735 non-null   int64
 3   reorder_point      8735 non-null   int64
 4   safety_stock       8735 non-null   int64
 5   last_restock_date  8735 non-null   object
 6   snapshot_date      8735 non-null   object
dtypes: int64(5), object(2)
memory usage: 477.8+ KB
None
============================================================
SKU
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku_id       200 non-null    int64
 1   sku_name     200 non-null    object
 2   category     200 non-null    object
 3   subcategory  200 non-null    object
 4   unit_price   200 non-null    float64
 5   cost_price   200 non-null    float64
 6   brand        200 non-null    object
dtypes: float64(2), int64(1), object(4)
memory usage: 11.1+ KB
None
============================================================
Stores
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   store_id      50 non-null     int64
 1   store_name    50 non-null     object
 2   city          50 non-null     object
 3   store_type    50 non-null     object
 4   opening_date  50 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.1+ KB
None
============================================================
Customers
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   cust_id            5000 non-null   int64
 1   age                5000 non-null   int64
 2   gender             5000 non-null   object
 3   city               5000 non-null   object
 4   loyalty_segment    5000 non-null   object
 5   preferred_channel  5000 non-null   object
 6   registration_date  5000 non-null   object
dtypes: int64(2), object(5)
memory usage: 273.6+ KB
None
============================================================
Promotions
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   promo_name    33 non-null     object
 1   start_date    33 non-null     object
 2   end_date      33 non-null     object
 3   discount_pct  33 non-null     int64
 4   promo_type    33 non-null     object
 5   promo_id      33 non-null     int64
dtypes: int64(2), object(4)
memory usage: 1.7+ KB
None

Check missing value

In [8]:
missing_report = {}

for name, df in datasets.items():

    missing = df.isnull().sum()

    print("\n")

    print("="*50)

    print(name)

    print("="*50)

    print(missing)

==================================================
Sales
==================================================
date                 0
store_id             0
sku_id               0
customer_id     159821
quantity             0
unit_price           0
total_value          0
channel              0
discount_pct         0
dtype: int64


==================================================
Inventory
==================================================
store_id             0
sku_id               0
stock_on_hand        0
reorder_point        0
safety_stock         0
last_restock_date    0
snapshot_date        0
dtype: int64


==================================================
SKU
==================================================
sku_id         0
sku_name       0
category       0
subcategory    0
unit_price     0
cost_price     0
brand          0
dtype: int64


==================================================
Stores
==================================================
store_id        0
store_name      0
city            0
store_type      0
opening_date    0
dtype: int64


==================================================
Customers
==================================================
cust_id              0
age                  0
gender               0
city                 0
loyalty_segment      0
preferred_channel    0
registration_date    0
dtype: int64


==================================================
Promotions
==================================================
promo_name      0
start_date      0
end_date        0
discount_pct    0
promo_type      0
promo_id        0
dtype: int64

Duplicate records

In [9]:
for name, df in datasets.items():

    duplicates = df.duplicated().sum()

    print(f"{name} Duplicate Rows : {duplicates}")

Sales Duplicate Rows : 45
Inventory Duplicate Rows : 0
SKU Duplicate Rows : 0
Stores Duplicate Rows : 0
Customers Duplicate Rows : 0
Promotions Duplicate Rows : 0

Data type

In [10]:
for name, df in datasets.items():

    print("="*50)

    print(name)

    print("="*50)

    print(df.dtypes)

==================================================
Sales
==================================================
date             object
store_id          int64
sku_id            int64
customer_id     float64
quantity          int64
unit_price      float64
total_value     float64
channel          object
discount_pct    float64
dtype: object
==================================================
Inventory
==================================================
store_id              int64
sku_id                int64
stock_on_hand         int64
reorder_point         int64
safety_stock          int64
last_restock_date    object
snapshot_date        object
dtype: object
==================================================
SKU
==================================================
sku_id           int64
sku_name        object
category        object
subcategory     object
unit_price     float64
cost_price     float64
brand           object
dtype: object
==================================================
Stores
==================================================
store_id         int64
store_name      object
city            object
store_type      object
opening_date    object
dtype: object
==================================================
Customers
==================================================
cust_id               int64
age                   int64
gender               object
city                 object
loyalty_segment      object
preferred_channel    object
registration_date    object
dtype: object
==================================================
Promotions
==================================================
promo_name      object
start_date      object
end_date        object
discount_pct     int64
promo_type      object
promo_id         int64
dtype: object

Statistical Summary

In [11]:
for name, df in datasets.items():

    print("="*60)

    print(name)

    print("="*60)

    display(df.describe(include='all'))

============================================================
Sales
============================================================

,date,store_id,sku_id,customer_id,quantity,unit_price,total_value,channel,discount_pct
count,641843,641843.000000,641843.000000,482022.000000,641843.000000,641843.000000,641843.000000,641843,641843.000000
unique,1765,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN
top,2021-05-02,NaN,NaN,NaN,NaN,NaN,NaN,Store,NaN
freq,965,NaN,NaN,NaN,NaN,NaN,NaN,274802,NaN
mean,NaN,25.491081,1100.547835,2504.986828,2.613120,44.109242,114.069845,NaN,5.411316
std,NaN,14.437269,57.684158,1442.340254,1.481563,48.984342,157.206354,NaN,8.664765
min,NaN,1.000000,1001.000000,1.000000,1.000000,1.700000,1.700000,NaN,0.000000
25%,NaN,13.000000,1051.000000,1260.000000,1.000000,14.280000,27.320000,NaN,0.000000
50%,NaN,25.000000,1101.000000,2507.000000,2.000000,24.330000,57.660000,NaN,0.000000
75%,NaN,38.000000,1150.000000,3752.000000,4.000000,49.570000,129.550000,NaN,10.000000
max,NaN,50.000000,1200.000000,5000.000000,6.000000,245.380000,1472.280000,NaN,35.000000

============================================================
Inventory
============================================================

,store_id,sku_id,stock_on_hand,reorder_point,safety_stock,last_restock_date,snapshot_date
count,8735.000000,8735.000000,8735.000000,8735.000000,8735.000000,8735,8735
unique,NaN,NaN,NaN,NaN,NaN,89,1
top,NaN,NaN,NaN,NaN,NaN,2025-09-10,2025-10-31
freq,NaN,NaN,NaN,NaN,NaN,117,8735
mean,25.343102,1100.295478,170.763938,67.755238,33.629193,NaN,NaN
std,14.385357,57.629837,77.875511,32.988546,16.499030,NaN,NaN
min,1.000000,1001.000000,35.000000,10.000000,5.000000,NaN,NaN
25%,13.000000,1051.000000,112.000000,43.000000,21.000000,NaN,NaN
50%,25.000000,1100.000000,156.000000,62.000000,31.000000,NaN,NaN
75%,38.000000,1150.000000,217.000000,87.000000,43.000000,NaN,NaN
max,50.000000,1200.000000,449.000000,217.000000,108.000000,NaN,NaN

============================================================
SKU
============================================================

,sku_id,sku_name,category,subcategory,unit_price,cost_price,brand
count,200.000000,200,200,200,200.000000,200.000000,200
unique,NaN,200,7,33,NaN,NaN,5
top,NaN,Electronics_Chargers_1001,Electronics,Batteries,NaN,NaN,Premium
freq,NaN,1,43,13,NaN,NaN,57
mean,1100.500000,NaN,NaN,NaN,46.682300,31.060100,NaN
std,57.879185,NaN,NaN,NaN,51.590508,34.435869,NaN
min,1001.000000,NaN,NaN,NaN,2.610000,1.680000,NaN
25%,1050.750000,NaN,NaN,NaN,15.242500,10.065000,NaN
50%,1100.500000,NaN,NaN,NaN,25.910000,17.115000,NaN
75%,1150.250000,NaN,NaN,NaN,51.270000,34.322500,NaN
max,1200.000000,NaN,NaN,NaN,245.380000,187.670000,NaN

============================================================
Stores
============================================================

,store_id,store_name,city,store_type,opening_date
count,50.00000,50,50,50,50
unique,NaN,50,3,3,50
top,NaN,BlueMart Store 09,Dubai,Mall,2017-01-01 00:00:00.000000000
freq,NaN,1,28,22,1
mean,25.50000,NaN,NaN,NaN,NaN
std,14.57738,NaN,NaN,NaN,NaN
min,1.00000,NaN,NaN,NaN,NaN
25%,13.25000,NaN,NaN,NaN,NaN
50%,25.50000,NaN,NaN,NaN,NaN
75%,37.75000,NaN,NaN,NaN,NaN
max,50.00000,NaN,NaN,NaN,NaN

============================================================
Customers
============================================================

,cust_id,age,gender,city,loyalty_segment,preferred_channel,registration_date
count,5000.000000,5000.000000,5000,5000,5000,5000,5000
unique,NaN,NaN,2,3,3,5,1675
top,NaN,NaN,Male,Dubai,Silver,Store,2023-08-06
freq,NaN,NaN,2849,2531,2915,2197,10
mean,2500.500000,31.097800,NaN,NaN,NaN,NaN,NaN
std,1443.520003,10.746689,NaN,NaN,NaN,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,NaN,NaN
25%,1250.750000,20.000000,NaN,NaN,NaN,NaN,NaN
50%,2500.500000,30.000000,NaN,NaN,NaN,NaN,NaN
75%,3750.250000,35.000000,NaN,NaN,NaN,NaN,NaN
max,5000.000000,60.000000,NaN,NaN,NaN,NaN,NaN

============================================================
Promotions
============================================================

,promo_name,start_date,end_date,discount_pct,promo_type,promo_id
count,33,33,33,33.000000,33,33.00000
unique,33,33,33,NaN,6,NaN
top,Ramadan Sale 2021,2021-04-13,2021-05-12,NaN,Eid,NaN
freq,1,1,1,NaN,10,NaN
mean,NaN,NaN,NaN,21.212121,NaN,17.00000
std,NaN,NaN,NaN,7.708589,NaN,9.66954
min,NaN,NaN,NaN,10.000000,NaN,1.00000
25%,NaN,NaN,NaN,15.000000,NaN,9.00000
50%,NaN,NaN,NaN,20.000000,NaN,17.00000
75%,NaN,NaN,NaN,25.000000,NaN,25.00000
max,NaN,NaN,NaN,35.000000,NaN,33.00000

Column name

In [12]:
for name, df in datasets.items():

    print("="*113)

    print(name)

    print("="*113)

    print(df.columns.tolist())

=================================================================================================================
Sales
=================================================================================================================
['date', 'store_id', 'sku_id', 'customer_id', 'quantity', 'unit_price', 'total_value', 'channel', 'discount_pct']
=================================================================================================================
Inventory
=================================================================================================================
['store_id', 'sku_id', 'stock_on_hand', 'reorder_point', 'safety_stock', 'last_restock_date', 'snapshot_date']
=================================================================================================================
SKU
=================================================================================================================
['sku_id', 'sku_name', 'category', 'subcategory', 'unit_price', 'cost_price', 'brand']
=================================================================================================================
Stores
=================================================================================================================
['store_id', 'store_name', 'city', 'store_type', 'opening_date']
=================================================================================================================
Customers
=================================================================================================================
['cust_id', 'age', 'gender', 'city', 'loyalty_segment', 'preferred_channel', 'registration_date']
=================================================================================================================
Promotions
=================================================================================================================
['promo_name', 'start_date', 'end_date', 'discount_pct', 'promo_type', 'promo_id']

Memory use

In [13]:
for name, df in datasets.items():

    memory = df.memory_usage(deep=True).sum() / 1024**2

    print(f"{name} Memory : {memory:.2f} MB")

Sales Memory : 104.39 MB
Inventory Memory : 1.32 MB
SKU Memory : 0.05 MB
Stores Memory : 0.01 MB
Customers Memory : 1.40 MB
Promotions Memory : 0.01 MB

Data Summary Table

In [14]:
summary = []

for name, df in datasets.items():

    summary.append({

        "Dataset": name,

        "Rows": df.shape[0],

        "Columns": df.shape[1],

        "Missing Values": df.isnull().sum().sum(),

        "Duplicates": df.duplicated().sum()

    })

summary_df = pd.DataFrame(summary)

summary_df

      Dataset    Rows  Columns  Missing Values  Duplicates
0       Sales  641843        9          159821          45
1   Inventory    8735        7               0           0
2         SKU     200        7               0           0
3      Stores      50        5               0           0
4   Customers    5000        7               0           0
5  Promotions      33        6               0           0

Save Summary

In [15]:
summary_df.to_csv(

    PROCESSED_DATA_PATH + "\\"+"dataset_summary.csv",

    index=False
)

print("Dataset Summary Saved")

Dataset Summary Saved

Primary Key Inspection

In [16]:
for name, df in datasets.items():

    print("="*60)

    print(name)

    print("="*60)

    for col in df.columns:

        if df[col].is_unique:

            print(col, "-> Possible Primary Key")

============================================================
Sales
============================================================
============================================================
Inventory
============================================================
============================================================
SKU
============================================================
sku_id -> Possible Primary Key
sku_name -> Possible Primary Key
============================================================
Stores
============================================================
store_id -> Possible Primary Key
store_name -> Possible Primary Key
opening_date -> Possible Primary Key
============================================================
Customers
============================================================
cust_id -> Possible Primary Key
============================================================
Promotions
============================================================
promo_name -> Possible Primary Key
start_date -> Possible Primary Key
end_date -> Possible Primary Key
promo_id -> Possible Primary Key

Foreign Key Inspection

In [17]:
common_columns = {}

for name, df in datasets.items():

    common_columns[name] = list(df.columns)

for name, cols in common_columns.items():

    print(name)

    print(cols)

    print()

Sales
['date', 'store_id', 'sku_id', 'customer_id', 'quantity', 'unit_price', 'total_value', 'channel', 'discount_pct']

Inventory
['store_id', 'sku_id', 'stock_on_hand', 'reorder_point', 'safety_stock', 'last_restock_date', 'snapshot_date']

SKU
['sku_id', 'sku_name', 'category', 'subcategory', 'unit_price', 'cost_price', 'brand']

Stores
['store_id', 'store_name', 'city', 'store_type', 'opening_date']

Customers
['cust_id', 'age', 'gender', 'city', 'loyalty_segment', 'preferred_channel', 'registration_date']

Promotions
['promo_name', 'start_date', 'end_date', 'discount_pct', 'promo_type', 'promo_id']

Data Dictionary

In [18]:
dictionary = []

for name, df in datasets.items():

    for col in df.columns:

        dictionary.append({

            "Dataset": name,

            "Column": col,

            "Data Type": df[col].dtype,

            "Missing": df[col].isnull().sum(),

            "Unique Values": df[col].nunique()

        })

dictionary_df = pd.DataFrame(dictionary)

dictionary_df.head()

  Dataset       Column Data Type  Missing  Unique Values
0   Sales         date    object        0           1765
1   Sales     store_id     int64        0             50
2   Sales       sku_id     int64        0            200
3   Sales  customer_id   float64   159821           5000
4   Sales     quantity     int64        0              6

Save Data Dictionary

In [19]:
dictionary_df.to_csv(

    PROCESSED_DATA_PATH + "\\" + "data_dictionary.csv",

    index=False
)

print("Data Dictionary Saved")

Data Dictionary Saved